[package]
name = "whisky-examples"
version = "0.6.7"
edition = "2021"
license = "Apache-2.0"
description = "The Cardano Rust SDK, inspired by MeshJS"

[dependencies]
whisky = { version = "=0.6.7", path = "../whisky" }
